### ISSUE TITLE
Host scanner on ARM64 does not work

### ISSUE THREAD

**Issue by lolo32** [kubescape/host-scanner#15]
# Describe the bug
The `DaeonSet` is successfully deployed, but every time, the hostscanner stays in `CrashLoopBackOff` at start.

The Pod log contains only:
```
exec ./kube-host-sensor: exec format error
```

I downloaded the image `quay.io/kubescape/host-scanner:v1.0.35` to check, and it's the same.

# Environment
```
OS: Linux 5.15.0-1021-oracle #27-Ubuntu SMP Fri Oct 14 20:04:20 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
Linux: Ubuntu 22.04.1 LTS
Version: v2.0.172
```

# Steps To Reproduce
1. Run a hostscanner with a kube containing an ARM64 host: `kubescape scan --enable-host-scan`

# Expected behavior
All work right without error

# Actual Behavior
The Pod stays in `CrashLoopBackOff`

# Additional context
I made these command to investigate:
```bash
# Retrieve the image on the host
$ docker pull quay.io/kubescape/host-scanner:v1.0.35

# The image was downloaded without any problem
$ docker image save quay.io/kubescape/host-scanner:v1.0.35 | tar xv

2dc561b874360f41fbb24505e750635afbfc3da75191cb226690667094ab0f61.json
54b1afaa52eb119c0d8eb6c8298ba785cb06134770f40a5a1656fc77ebf32cc7/
54b1afaa52eb119c0d8eb6c8298ba785cb06134770f40a5a1656fc77ebf32cc7/VERSION
54b1afaa52eb119c0d8eb6c8298ba785cb06134770f40a5a1656fc77ebf32cc7/json
54b1afaa52eb119c0d8eb6c8298ba785cb06134770f40a5a1656fc77ebf32cc7/layer.tar
72528bc5c69b9f4f8dd8d685d1ffa658a69a9eb815aeea6f9f54a3a070b7b556/
72528bc5c69b9f4f8dd8d685d1ffa658a69a9eb815aeea6f9f54a3a070b7b556/VERSION
72528bc5c69b9f4f8dd8d685d1ffa658a69a9eb815aeea6f9f54a3a070b7b556/json
72528bc5c69b9f4f8dd8d685d1ffa658a69a9eb815aeea6f9f54a3a070b7b556/layer.tar
manifest.json
repositories

# Extracted the first layer
$ cd 72528bc5c69b9f4f8dd8d685d1ffa658a69a9eb815aeea6f9f54a3a070b7b556
$ tar xf layer.tar

# Checked the architecture of the binary
$ file bin/busybox

bin/busybox: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-aarch64.so.1, stripped

$cd ..
# Extracted the second layer
$ cd 54b1afaa52eb119c0d8eb6c8298ba785cb06134770f40a5a1656fc77ebf32cc7
$ tar xvf layer.tar

kube-host-sensor

# Checked the architecture of the binary
$ file kube-host-sensor

kube-host-sensor: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=_MDqQEPq5W5_wU8AWG1H/JWTZrNxTFKoqV5w8mZW0/Rd383K46e_qWKJyGf2Pu/NjUPnzF3NTah5VQVrhmj, stripped
```
And on `kube-host-sensor`, there is a problem, the binary is for `x86-64`…

After some search, I found the source of the problem, I think, directly inside the Dockerfile:
https://github.com/kubescape/host-scanner/blob/0b7c5c06a741bfab15a20c54b2808c2c471b6544/build/Dockerfile#L7

You specify to build for `GOARCH=amd64`, even for building ARM64 image

**Comment by lolo32** [comment]
I just tested it:
```bash
$ docker clone https://github.com/kubescape/host-scanner
$ cd host-scanner
$ vim build/Dockerfile

# removed `GOOS=linux GOARCH=amd64` from the line 7

$ docker build -t lolo32/kubecape-host-scanner:latest-arm64 -f buid/Dockerfile .
$ docker push lolo32/kubecape-host-scanner:latest-arm64
```
I made the same for amd64, then I changed the `DaemonSet` image to this one, and it works like a charm, no more errors.

**Comment by shm12** [comment]
Hi @lolo32!
Thanks for making efforts, in both, the issue and the PR. The issue you pointed out Is a good one.
The PR fixes only a part of the problem though. We have to add the support for multi-architecture in the official image, in the GitHub action build.

I won't be able to do it, but whoever wants to contribute it, may want to use this article https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

@kooomix Do you want to take it?

**Comment by lolo32** [comment]
> I won't be able to do it, but whoever wants to contribute it, may want to use this article https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

Hi @shm12, I do not think the post you mention is up to date for using buildx.

Maybe looking at https://github.com/docker/setup-buildx-action
