### ISSUE TITLE
Repo should be tagged and produce images accordingly

### ISSUE THREAD

**Issue by fredbi** [kubescape/host-scanner#38]
## Overview
At this moment, it is difficult to figure out which version of this repo corresponds to the tagged image available on quay.io.

## Problem
I've noticed this when working on the client-side calling the host-scanner API in a package in kubescape (kubescape/core/pkg/hostsensorutils): routes are hard-coded there and we don't really know which is which.

## Solution
1. Tag the host-scanner repo
2. Build images according to the tag

**Comment by fredbi** [comment]
cc: @dwertent @matthyx

**Comment by matthyx** [comment]
I think this is intentional @dwertent ?
