### ISSUE TITLE
host scanner pods are restarting continuosly with probe related errors - Azure AKS v1.25.6

### ISSUE THREAD

**Issue by zohebk8s** [kubescape/host-scanner#53]
Hi Team,

I am trying to scan Azure AKS Node by deploying a host scanner. But host scanner pods are continuously restarting with probe-related errors.

Azure AKS Version - v1.25.6

I've used below command to deploy the host scanner in azure aks:

kubectl apply -f https://raw.githubusercontent.com/kubescape/kubescape/master/core/pkg/hostsensorutils/hostsensor.yaml

Error:

`shaik [ ~ ]$ kubectl get events -n kubescape | grep -i probe
15s         Warning   Unhealthy          pod/host-scanner-5rmdl   Startup probe failed: Get "http://10.224.0.196:7888/readyz": dial tcp 10.224.0.196:7888: connect: connection refused
2m28s       Warning   Unhealthy          pod/host-scanner-8chcc   Startup probe failed: Get "http://10.224.0.144:7888/readyz": dial tcp 10.224.0.144:7888: connect: connection refused
57s         Warning   Unhealthy          pod/host-scanner-bnmjz   Startup probe failed: Get "http://10.224.0.171:7888/readyz": dial tcp 10.224.0.171:7888: connect: connection refused
3m13s       Warning   Unhealthy          pod/host-scanner-c7lqd   Startup probe failed: Get "http://10.224.0.151:7888/readyz": dial tcp 10.224.0.151:7888: connect: connection refused
2m29s       Warning   Unhealthy          pod/host-scanner-fg7d8   Startup probe failed: Get "http://10.224.1.108:7888/readyz": dial tcp 10.224.1.108:7888: connect: connection refused
90s         Warning   Unhealthy          pod/host-scanner-fh94r   Startup probe failed: Get "http://10.224.1.31:7888/readyz": dial tcp 10.224.1.31:7888: connect: connection refused
115s        Warning   Unhealthy          pod/host-scanner-gfsvm   Startup probe failed: Get "http://10.224.1.43:7888/readyz": dial tcp 10.224.1.43:7888: connect: connection refused
16s         Warning   Unhealthy          pod/host-scanner-jft8x   Startup probe failed: Get "http://10.224.1.139:7888/readyz": dial tcp 10.224.1.139:7888: connect: connection refused
57s         Warning   Unhealthy          pod/host-scanner-jjxm6   Startup probe failed: Get "http://10.224.1.74:7888/readyz": dial tcp 10.224.1.74:7888: connect: connection refused
2m18s       Warning   Unhealthy          pod/host-scanner-mpdmz   Startup probe failed: Get "http://10.224.1.11:7888/readyz": dial tcp 10.224.1.11:7888: connect: connection refused
2m51s       Warning   Unhealthy          pod/host-scanner-nbpzf   Startup probe failed: Get "http://10.224.0.118:7888/readyz": dial tcp 10.224.0.118:7888: connect: connection refused
2m28s       Warning   Unhealthy          pod/host-scanner-nn6w8   Startup probe failed: Get "http://10.224.1.3:7888/readyz": dial tcp 10.224.1.3:7888: connect: connection refused
2m51s       Warning   Unhealthy          pod/host-scanner-qp5f5   Startup probe failed: Get "http://10.224.0.251:7888/readyz": dial tcp 10.224.0.251:7888: connect: connection refused
15s         Warning   Unhealthy          pod/host-scanner-wmxhn   Startup probe failed: Get "http://10.224.0.226:7888/readyz": dial tcp 10.224.0.226:7888: connect: connection refused
58s         Warning   Unhealthy          pod/host-scanner-wv4tg   Startup probe failed: Get "http://10.224.1.157:7888/readyz": dial tcp 10.224.1.157:7888: connect: connection refused
7m20s       Warning   Unhealthy          pod/host-scanner-z49cl   Startup probe failed: Get "http://10.224.0.252:7888/readyz": dial tcp 10.224.0.252:7888: connect: connection refused`

**Comment by alegrey91** [comment]
Hi @zohebk8s, thanks for opening the issue.
First of all, can you please provide also the output of: 
* `kubectl describe pod host-scanner-z49cl -n kubescape`
* `kubectl logs host-scanner-z49cl -n kubescape`

Then, is there some reason why you are deploying `host-scanner` using the manifest instead of enable it from `kubescape`?

**Comment by zohebk8s** [comment]
@alegrey91 I was not aware of that option. Usually I’m using add cluster, copy the helm command and run in on AKS.

It would be great if you can share the deployment step for enabling it at the time of KubeScape installation or from Kubescape portal.

It’s working now. After multiple restarts

**Comment by alegrey91** [comment]
> It’s working now. After multiple restarts

Good to know!

So, if you are using the `kubescape` CLI, then you can enable the `host-scanner` simply by running this command:
```
kubescape scan --enable-host-scan
```

If you are using the operator with helm-chart, then you can enable it by adding this flag to the command: `--set kubescape.enableHostScan=true`
See documentation here: https://github.com/kubescape/helm-charts/blob/main/charts/kubescape-cloud-operator/README.md

The `host-scanner` will enrich the data from your cluster, so you can have a more exhaustive result.

If you have other questions feel free to answer!

**Comment by zohebk8s** [comment]
@alegrey91 Thanks for sharing the details.
